apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: ">=4.10.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  install:
    createNamespace: false
  values:
    controller:
      ingressClassResource:
        name: nginx
        default: true
      service:
        type: LoadBalancer
      metrics:
        enabled: true
