apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
  labels: { k8s-app: nvidia-device-plugin }
spec:
  selector:
    matchLabels: { name: nvidia-device-plugin-ds }
  updateStrategy: { type: RollingUpdate }
  template:
    metadata:
      labels: { name: nvidia-device-plugin-ds }
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
        - image: "nvidia/k8s-device-plugin:1.15.0"
          name: nvidia-device-plugin-ctr
          args: ["--fail-on-init-error=false"]
          securityContext: { allowPrivilegeEscalation: false }
          resources:
            requests: { cpu: "10m", memory: "20Mi" }
            limits:   { cpu: "100m", memory: "200Mi" }
