apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-installer
  namespace: kube-system
  labels:
    k8s-app: nvidia-driver-installer
spec:
  selector:
    matchLabels:
      name: nvidia-driver-installer-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-driver-installer-ds
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
        - name: nvidia-driver-installer
          image: "gcr.io/gke-release/nvidia-driver-installer:latest"
          securityContext:
            privileged: true
          resources:
            requests: { cpu: "50m", memory: "200Mi" }
            limits:   { cpu: "500m", memory: "1Gi" }
