apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuberay-operator
  namespace: kuberay
spec:
  interval: 5m
  chart:
    spec:
      chart: kuberay-operator
      version: "1.4.2"
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: kuberay
  install:
    createNamespace: false
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  values:
    image:
      pullPolicy: IfNotPresent
