apiVersion: v1
kind: Namespace
metadata:
  name: ray
---
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-serve
  namespace: ray
spec:
  serveConfigV2: |
    http_options:
      host: 0.0.0.0
      port: 8000
    applications:
      - name: transformer-pipeline-sentiment-v7
        route_prefix: /infer
        import_path: "serve_app:graph"
  rayClusterConfig:
    rayVersion: "2.9.0"
    enableInTreeAutoscaling: true
    headGroupSpec:
      serviceType: ClusterIP
      rayStartParams: { dashboard-host: "0.0.0.0" }
      template:
        spec:
          nodeSelector: { pool: "cpu" }
          containers:
            - name: ray-head
              image: "jeroendenboef/jdb-personal-dev:ray-serve-2.9.0-app.7"
              imagePullPolicy: IfNotPresent
              resources:
                requests: { cpu: "500m", memory: "2Gi" }
                limits:   { cpu: "1",    memory: "4Gi" }
              ports:
                - name: dashboard
                  containerPort: 8265
                - name: serve
                  containerPort: 8000
                - name: client
                  containerPort: 10001
                - name: gcs
                  containerPort: 6379
    workerGroupSpecs:
      - groupName: cpu-workers
        replicas: 0
        minReplicas: 0
        maxReplicas: 2
        rayStartParams: {}
        template:
          spec:
            nodeSelector: { pool: "cpu" }
            containers:
              - name: ray-worker
                image: "jeroendenboef/jdb-personal-dev:ray-serve-2.9.0-app.7"
                resources:
                  requests: { cpu: "500m", memory: "2Gi" }
                  limits:   { cpu: "1",    memory: "4Gi" }
      - groupName: gpu-workers
        replicas: 0
        minReplicas: 0
        maxReplicas: 1
        rayStartParams: {}
        template:
          spec:
            nodeSelector:
              pool: "gpu"
              cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Exists"
                effect: "NoSchedule"
            containers:
              - name: ray-worker
                image: "jeroendenboef/jdb-personal-dev:ray-serve-2.9.0-app.7"
                resources:
                  limits:
                    nvidia.com/gpu: 1
                    cpu: "2"
                    memory: "8Gi"
                  requests:
                    nvidia.com/gpu: 1
                    cpu: "1"
                    memory: "4Gi"
